name: dus_case_camp
description: A weekly case-based training platform for dentistry students.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  video_player: ^2.9.0
  chewie: ^1.8.1
  intl: any
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  fl_chart: ^1.1.1
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
